services:
  - type: worker
    name: archimeets-forwarder
    runtime: python
    pythonVersion: 3.11.7
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    region: oregon
